// <auto-generated />
using EcoBiteWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoBiteWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240921055948_SeedFooditemTable")]
    partial class SeedFooditemTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoBiteWeb.Models.Fooditem", b =>
                {
                    b.Property<int>("FooditemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FooditemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FooditemId");

                    b.ToTable("Fooditems");

                    b.HasData(
                        new
                        {
                            FooditemId = 1,
                            Description = "Available",
                            ExpirationDate = "29 days",
                            Name = "Rice"
                        },
                        new
                        {
                            FooditemId = 2,
                            Description = "Availabel",
                            ExpirationDate = "5 days",
                            Name = "Burger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
